name: Deploying InnoSchedule to Vercel
env:
  ORG_ID: ${{ secrets.ORG_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
on:
  push:
    branches:
      - main
      - F12-pipeline
jobs:
   Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Run linter
        run: npm run lint
      - name: Run format checking
        run: npm run check
   Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm
